### PR TITLE
WIP: Fix flaky CI

### PR DESCRIPTION
**Pull request by typesanitizer**
I've just made this dummy PR where I can change things and see how the CI responds (so I can fix the problem) -- I couldn't figure out a way to get CI on my forked repo. Once/If I figure out how to reliably get it to succeed/fail (i.e. we identify the root cause of the flakiness), we can merge the fix.

I've added a dummy package to install to make sure the CI is re-run.

### CODE REVIEW

**Comment by typesanitizer** [comment]
Hmm, why is Travis not running again? Have you disabled it?

**Comment by banacorn** [comment]
The CI is not running because it's set to only run on branch `master` or with tags like `v****`

You can tune this or remove the whole section in `.travis.yml`.
```yaml
branches:
  only:
  - master
  - "/^v.*$/"
```

**Comment by typesanitizer** [comment]
It seemed like draft PRs are also not tested by Travis, which is why it wasn't triggering.

**Comment by typesanitizer** [comment]
I've tried doing multiple things including using the `CXXFLAGS="-std=c++11"` environmental variable but it doesn't work for some reason. I'll try to think of some alternate solutions over the weekend.

**Comment by banacorn** [comment]
I'm trying to run 08cf249 on the CI, but something terrible happens on both the osx and linux build.
@theindigamer sorry that I'm not so familiar with C++, can you help me on this?

https://travis-ci.org/tree-sitter/tree-sitter-agda/builds/532098086
```
 CXX(target) Release/obj.target/tree_sitter_agda_binding/src/binding.o
../src/binding.cc:13:6: error: variable has incomplete type 'void'
void Init(Handle<Object> exports, Handle<Object> module) {
     ^
../src/binding.cc:13:11: error: use of undeclared identifier 'Handle'
void Init(Handle<Object> exports, Handle<Object> module) {
          ^
../src/binding.cc:13:18: error: 'Object' does not refer to a value
void Init(Handle<Object> exports, Handle<Object> module) {
                 ^
/Users/travis/.node-gyp/12.2.0/include/node/v8.h:3356:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/binding.cc:13:26: error: use of undeclared identifier 'exports'
void Init(Handle<Object> exports, Handle<Object> module) {
                         ^
../src/binding.cc:13:35: error: use of undeclared identifier 'Handle'
void Init(Handle<Object> exports, Handle<Object> module) {
                                  ^
../src/binding.cc:13:42: error: 'Object' does not refer to a value
void Init(Handle<Object> exports, Handle<Object> module) {
                                         ^
/Users/travis/.node-gyp/12.2.0/include/node/v8.h:3356:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/binding.cc:13:50: error: use of undeclared identifier 'module'
void Init(Handle<Object> exports, Handle<Object> module) {
                                                 ^
../src/binding.cc:13:57: error: expected ';' after top level declarator
void Init(Handle<Object> exports, Handle<Object> module) {
                                                        ^
                                                        ;
8 errors generated.
make: *** [Release/obj.target/tree_sitter_agda_binding/src/binding.o] Error 1
```

**Comment by typesanitizer** [comment]
@banacorn sorry I've been a bit busy, I'll try to take a look and fix this on the weekend!

**Comment by banacorn** [comment]
After hours of fiddling, I found that not just Travis CI, but `node-gyp` is also kinda bad at supporting C11. 
There are no other tree-sitter packages that are using C11 (tree-sitter-ruby tried but dropped it soon), perhaps we should just stick to C99.

**Comment by banacorn** [comment]
All green now! @theindigamer thanks for your help, I just can't handle C++ without you.

**Pull request merged**
