### PR TITLE
Update to add new tree-sitter system

### PR DESCRIPTION
**Pull request by auscyber**
Add new tree-sitter system to allow for integration with nvim-treesitter
Added queries for highlighting and minimal folds

### CODE REVIEW

**Comment by Decodetalkers** [comment]
Does your treesitter have better support?

**Comment by Decodetalkers** [comment]
If the author does not want to maintain this repo, you can maintain another

**Comment by Decodetalkers** [comment]
and your highlight is good enough, you can try to make pr to nvim-treesitter

**Comment by amaanq** [comment]
I don't understand the CI failure, it works fine for me locally and off a fresh clone, just gonna merge

**Pull request merged**
